### ISSUE TITLE
REPL模式快捷键似乎错了

### ISSUE THREAD

**Issue by yym0924** [hyper0x/JuliaBasics#2]
[2.1.3 快捷键](https://github.com/hyper0x/JuliaBasics/blob/master/book/ch02.md#213-快捷键)
头两个快捷键似乎改成下面的才对？
- `Alt+B` ：将光标移动到左边最近的单词开始处。
- `Alt+F`：将光标移动到右边最近的单词末尾处之后。
- `Ctrl+←`：将光标移动到左边最近的单词开始处。
- `Ctrl+→`：将光标移动到右边最近的单词末尾处之后。

---
顺便期待正式出版的书籍早日来到，和目前市面上现有的中文实体书和在线教程中这本书应该是最适合入门的了。❤

**Comment by hyper0x** [comment]
谢谢！不过，我试验了一下，在我的电脑中，`Alt+←`和`Alt+→` 的作用是符合现有描述的。而你写的这四个快键键，在我的REPL环境中都无效。

我的操作系统是：macOS
我的Julia 版本是：1.3.1

你的呢？

**Comment by yym0924** [comment]
> 谢谢！不过，我试验了一下，在我的电脑中，`Alt+←`和`Alt+→` 的作用是符合现有描述的。而你写的这四个快键键，在我的REPL环境中都无效。
> 
> 我的操作系统是：macOS
> 我的Julia 版本是：1.3.1
> 
> 你的呢？

我的Julia版本也是1.3.1，Windows和Linux下我都实验了，快捷键是我描述的情况。 @hyper0x

**Comment by hyper0x** [comment]
安装了一下虚拟机，对于不同操作系统，快捷键确实有所不同。已改进相关内容。
