### ISSUE TITLE
关于Linux仓库目录

### ISSUE THREAD

**Issue by yym0924** [hyper0x/JuliaBasics#3]
[**2.2.1 仓库目录**](https://github.com/hyper0x/JuliaBasics/blob/master/book/ch02.md#221-%E4%BB%93%E5%BA%93%E7%9B%AE%E5%BD%95)
如果是系统自带软件源root安装的话确实是文中所示的路径。不过如果是直接下载官网的二进制文件解压后使用的话，后两个路径应该是julia安装目录下的对应文件，比如我安装在/opt/julia-1.3.1/
``` 
"/opt/julia-1.3.1/local/share/julia"
"/opt/julia-1.3.1/share/julia"
```
以及可否考虑注明下Linux下第一个目录为`"/home/haolin/.julia" ` （虽然熟悉Linux的读者应该脑袋里就自动转换了）

**Comment by hyper0x** [comment]
好的，我后面改进一下，改完了再close这个issue。现在正在赶第15章：）

**Comment by hyper0x** [comment]
已改进相关内容。
