### ISSUE TITLE
错别字

### ISSUE THREAD

**Issue by yym0924** [hyper0x/JuliaBasics#4]
[**1.2 安装和启动**](https://github.com/hyper0x/JuliaBasics/blob/master/book/ch01.md#12-%E5%AE%89%E8%A3%85%E5%92%8C%E5%90%AF%E5%8A%A8)
这里讲到julia命令的参数的`-i`后面的

> 从字面上我们也可以了解到，该环境会读取你输入的表达式、对读到的表达式进行**求职**、显示表达式的求值结果，然后再次等待读取。
“求职”处是个错别字。

**Comment by hyper0x** [comment]
收到，我修正一下，谢谢。
