### ISSUE TITLE
将部分测试例子放在Julia Jupyter NoteBook测试，并且展示。建议

### ISSUE THREAD

**Issue by GTrunSec** [hyper0x/JuliaBasics#6]
目前提供了https://github.com/GTrunSec/Jupyter-data-science-environment/blob/master/default.nix
Julia的kernel版本，并且添加CUDA。
希望能迁移部分实例测试到Jupyter-notebook。我这边可以为您提供各种环境，包括CUDA，并且为你放一个Julia Jupyter kernel 测试Http接口。助力Julia，当然你如果有意向

**Comment by GTrunSec** [comment]
这个类似于 https://mybinder.org/ 但是实现是用nix.目前包和环境是我主要维护。开放的http接口可以用Jupyterlab-git进行仓库管理。
- 缘由是因为，国内做科学分析Julia Haskell的太少，而且没有好的教程和Jupyter实例。直到看的你的Julia教学。然后这边我正好手头有资源（机器，GPU等），可以长期维护一个环境。而且使用nix后，可以打打减少我维护的成本，和滚动更新。以及提供给别人一个快速分析场景。
![image](https://user-images.githubusercontent.com/21156405/82524271-5c98e880-9ae3-11ea-8daa-0dbcbe4b13a5.png)

**Comment by hyper0x** [comment]
哈喽，看起来挺好玩的。不过这是一本入门书，暂时还用不到这么炫酷的东西。我觉得应该先让初学者们习惯在 REPL 和 .jl 文件里写代码。等以后我如果再出其他的高级课程，我会考虑。谢谢啦！
